---
title: "R_project_log"
author: "Jakub Piasek"
date: "2024-05-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set("~/ds/studia/sem2/r/r_project")
```

# TODO - poukładać i poopisywać ładnie wcześniejsze dni

## 30.05.2024
- Znalezienie danych

## 31.05.2024
- Zebranie wszystkich urlów

## 1.06.2024
- Pliki scraping.R i url_list.R
- Zliczenie wszystkich rekordów

## 2.06.2024
- Rozpoczęcie czyszczenia danych
- Usunięcie kolumny "Pos" (duplikującej) z ramek danych, w których występowała
- Utworzenie funkcji, która zastępuje stare ramki danych na nowe w środowisku globalnym
# TODO - wyeksportować wyczyszczone dane do folderu clean_data


## 3.06.2024


## 4.06.2024
- Utworzyłem `artist_genre_comparison`, czyli data frame łączący statystyki artystów ze wszystkich serwisów, do tego zsumowałem wszystkie statystyki dotyczące słuchaczy/wyświetleń do jednej kolumny `Sum_listeners_views_across`, a także przypisałem każdemu artyście odpowiedni (ogólny) gatunek
- Czyszczenie kolumn w `artist_genre_comparison` i ich nazw
- Problem: odpowiednie łączenie po kolei ramek danych za pomocą `join()`


## 5.06.2024
- packrat - package dependencies
- Data import/export pipeline
- Problem: poprawna kolejność pipelinu oraz pozbycie się ".csv" z nazw importowanych zmiennych
- Wizualizacja najchętniej słuchanych gatunków na wszystkich platformach




[Reference 1](https://www.kaggle.com/code/kuanminhuang/spotify-data-analysis)
[Reference 2](https://www.thesocialskinny.com/comparison-of-streaming-services/)
[Reference 3](https://www.slideshare.net/slideshow/music-streaming-industry-analysis-65641415/65641415)
[Reference 4](https://en.wikipedia.org/wiki/Comparison_of_music_streaming_services)
[Reference 5 - more song meta variables](https://github.com/lorenzotinfena/spotify-music-analysis/blob/main/src/notebook.ipynb)

# TODO - CODE
- najchętniej słuchani artyści w polsce (across all dsp)
- najchętniej słuchane gatunki w polsce (across all dsp)
- najchętniej słuchane piosenki + w polsce (across al dsp)

- na której platforamie ludzie najwięcej słuchają
- na której platformie najwięcej ludzi słucha

- top spotify songs/artists + w polsce
- top apple songs/artists + w polsce
- top yt songs/artists + w polsce

- proportion of songs by top artists

- różnica w piosenkach (których tracków brakuje across all dsp)
- różnica w artystach (których artystów brakuje across all dsp)

- correlation heatmap between variables
- clustering for artists/genres
- total number of songs since each year?
- song duration comparison?

- ogarnąć loudnes/energy itd variables

- różnice pomiędzy 



# TODO - MARKDOWN
- Understanding the data
- Który serwis do kogo trafi najlepiej (poprzez rekomendacje itd.)
- porównać koszt każdego z nich