---
title: "R_project_main"
author: "Jakub Piasek"
date: "2024-05-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set("~/ds/studia/sem2/r/r_project")
```


```{r cache=FALSE, echo=FALSE, results=FALSE}
library('lintr')

source("scraping.R", echo = T, local = knitr::knit_global())
knitr::read_chunk('scraping.R')
```


```{r scraping.R, eval=T}

```


Ilość rekordów we wszystkich ramkach danych

```{r}
total_rows <- ls() %>%
  set_names() %>%
  map(~ get(.)) %>%
  keep(is.data.frame) %>%
  map_int(nrow) %>%
  sum()


total_rows

total_rows > 30000
```

# Czyszczenie danych

### Usuwanie kolumny "Pos"
Aby uniknąć duplikatów w kolumnach, należy usunąć kolumnę "Pos"

```{r}
source("cleaning.R", echo = T, local = knitr::knit_global())
knitr::read_chunk('cleaning.R')
```

```{r cleaning.R, eval=T}

```


# TODO - sklasyfikować jakie gatunki są najchętniej słuchane (relacja: artysta - gatunek) pomiędzy wszystkimi platformami, użyć MusicOSet

```{r}
# Data frame containing metadata about artists
OSet_artists <- import("clean_data/musicoset_metadata/artists.csv")

# OSet_artists genre variables unification
OSet_artists <- OSet_artists %>%
  mutate(main_genre = case_when(
    grepl("rap", main_genre) ~ "rap",
    grepl("hip hop", main_genre) ~ "rap",
    grepl("drill", main_genre) ~ "rap",
    grepl("rock", main_genre) ~ "rock",
    grepl("country", main_genre) ~ "country",
    grepl("r&b", main_genre) ~ "r&b",
    grepl("edm", main_genre) ~ "edm",
    .default = as.character(main_genre)
  ))

OSet_artists_genre <- OSet_artists %>%
  select(c("name", "main_genre"))

```




```{r}
# which data frames have artist variables

# eu_artisttotals - only in europe
# eua_artisttotals - based on albums - only in europe
# ww_artisttotals
# spotify_listeners
# youtube_archive
# apple_songs_artisttotals
# apple_songs_eu_artisttotals - only in europe

artists_genre_comparison <- ww_artisttotals%>%
  inner_join(
    spotify_listeners,
    by = "Artist",
    suffix = c(".ww", ".spotify")
  ) %>%
  inner_join(
    youtube_archive,
    by = "Artist",
    suffix = c(".ww", ".youtube")
  ) %>%
  inner_join(
    apple_songs_artisttotals,
    by = "Artist",
    suffix = c(".ww", ".apple")
  )

# Test to see if the are no duplicate rows
artists_genre_comparison %>%
  filter(Artist == "Adele")


# Column cleaning
artists_genre_comparison$Total.youtube <- str_replace_all(artists_genre_comparison$Total.youtube, ",","")
artists_genre_comparison$Total.ww <- str_replace_all(artists_genre_comparison$Total.ww, ",", "")
artists_genre_comparison$PkListeners <- str_replace_all(artists_genre_comparison$PkListeners, ",", "")
artists_genre_comparison$Total <- str_replace_all(artists_genre_comparison$Total, ",", "")

artists_genre_comparison <- artists_genre_comparison %>%
  transform(
    Total.youtube = as.numeric(Total.youtube)
  ) %>%
  transform(
    Total.ww = as.numeric(Total.ww)
  ) %>%
  transform(
    PkListeners = as.numeric(PkListeners)
  ) %>%
  transform(
    Total = as.numeric(Total)
  ) %>%
  mutate(
    # Total.youtube column is equal to total views in millions
    Total.youtube = as.numeric(Total.youtube) * 1000000
  )


# Sum column
artists_genre_comparison <- artists_genre_comparison %>%
  mutate(
    sum = Total.youtube + Total.ww + Total + PkListeners
  ) %>%
  arrange(desc(sum))

```

